Todas_Compras = [{'name': 'Amber Staff', 'quantity': 85},
{'name': 'Ancient Amulet', 'quantity': 169},
{'name': 'Angelic Axe', 'quantity': 0},
{'name': 'Assassin Dagger', 'quantity': 23},
{'name': 'Beastslayer Axe', 'quantity': 87},
{'name': 'Blue Robe', 'quantity': 72},
{'name': 'Bone Shield', 'quantity': 0},
{'name': 'Boots Of Haste', 'quantity': 62},
{'name': 'Broadsword', 'quantity': 66},
{'name': 'Butchers Axe', 'quantity': 178},
{'name': 'Composite Hornbow', 'quantity': 0},
{'name': 'Crown Armor', 'quantity': 384},
{'name': 'Crown Helmet', 'quantity': 169},
{'name': 'Crown Legs', 'quantity': 176},
{'name': 'Crown Shield', 'quantity': 182},
{'name': 'Crusader Helmet', 'quantity': 69},
{'name': 'Crystal Necklace', 'quantity': 178},
{'name': 'Crystal Ring', 'quantity': 167},
{'name': 'Crystal Sword', 'quantity': 98},
{'name': 'Daramian Waraxe', 'quantity': 4},
{'name': 'Dark Shield', 'quantity': 32},
{'name': 'Death Ring', 'quantity': 173},
{'name': 'Demon Shield', 'quantity': 12},
{'name': 'Demonbone Amulet', 'quantity': 0},
{'name': 'Demonrage Sword', 'quantity': 0},
{'name': 'Devil Helmet', 'quantity': 34},
{'name': 'Diamond Sceptre', 'quantity': 43},
{'name': 'Divine Plate', 'quantity': 0},
{'name': 'Djinn Blade', 'quantity': 0},
{'name': 'Dragon Hammer', 'quantity': 10},
{'name': 'Dragon Scale Mail', 'quantity': 5},
{'name': 'Dragon Shield', 'quantity': 76},
{'name': 'Dragon Slayer', 'quantity': 10},
{'name': 'Dragonbone Staff', 'quantity': 76},
{'name': 'Dreaded Cleaver', 'quantity': 2},
{'name': 'Elvish Bow', 'quantity': 0},
{'name': 'Emerald Bangle', 'quantity': 98},
{'name': 'Epee', 'quantity': 16},
{'name': 'Fire Axe', 'quantity': 296},
{'name': 'Fire Sword', 'quantity': 542},
{'name': 'Flower Dress', 'quantity': 0},
{'name': 'Flower Wreath', 'quantity': 2},
{'name': 'Fur Boots', 'quantity': 0},
{'name': 'Furry Club', 'quantity': 24},
{'name': 'Glacier Amulet', 'quantity': 23},
{'name': 'Glacier Kilt', 'quantity': 0},
{'name': 'Glacier Mask', 'quantity': 0},
{'name': 'Glacier Robe', 'quantity': 0},
{'name': 'Glacier Shoes', 'quantity': 0},
{'name': 'Glorious Axe', 'quantity': 482},
{'name': 'Gold Ring', 'quantity': 10},
{'name': 'Golden Armor', 'quantity': 6},
{'name': 'Golden Legs', 'quantity': 3},
{'name': 'Guardian Halberd', 'quantity': 0},
{'name': 'Guardian Shield', 'quantity': 680},
{'name': 'Hammer Of Wrath', 'quantity': 0},
{'name': 'Haunted Blade', 'quantity': 18},
{'name': 'Heavy Trident', 'quantity': 2},
{'name': 'Heroic Axe', 'quantity': 0},
{'name': 'Hibiscus Dress', 'quantity': 48},
{'name': 'Ice Rapier', 'quantity': 151},
{'name': 'Jade Hammer', 'quantity': 0},
{'name': 'Knight Armor', 'quantity': 42},
{'name': 'Knight Legs', 'quantity': 26},
{'name': 'Lightning Headband', 'quantity': 34},
{'name': 'Lightning Legs', 'quantity': 8},
{'name': 'Lightning Pendant', 'quantity': 163},
{'name': 'Lightning Robe', 'quantity': 2},
{'name': 'Lunar Staff', 'quantity': 5},
{'name': 'Magic Plate Armor', 'quantity': 0},
{'name': 'Magma Amulet', 'quantity': 0},
{'name': 'Magma Boots', 'quantity': 12},
{'name': 'Magma Coat', 'quantity': 0},
{'name': 'Magma Legs', 'quantity': 0},
{'name': 'Magma Monocle', 'quantity': 0},
{'name': 'Mastermind Shield', 'quantity': 4},
{'name': 'Medusa Shield', 'quantity': 33},
{'name': 'Mercenary Sword', 'quantity': 106},
{'name': 'Mycological Bow', 'quantity': 0},
{'name': 'Nightmare Blade', 'quantity': 40},
{'name': 'Noble Axe', 'quantity': 0},
{'name': 'Obsidian Lance', 'quantity': 23},
{'name': 'Onyx Flail', 'quantity': 2},
{'name': 'Onyx Pendant', 'quantity': 0},
{'name': 'Oriental Shoes', 'quantity': 9},
{'name': 'Paladin Armor', 'quantity': 0},
{'name': 'Pirate Voodoo Doll', 'quantity': 110},
{'name': 'Platinum Amulet', 'quantity': 176},
{'name': 'Relic Sword', 'quantity': 10},
{'name': 'Rift Bow', 'quantity': 0},
{'name': 'Rift Crossbow', 'quantity': 0},
{'name': 'Rift Lance', 'quantity': 2},
{'name': 'Rift Shield', 'quantity': 0},
{'name': 'Ring Of The Sky', 'quantity': 8},
{'name': 'Ring Of the Sky', 'quantity': 0},
{'name': 'Royal Helmet', 'quantity': 35},
{'name': 'Ruby Necklace', 'quantity': 19},
{'name': 'Sacred Tree Amulet', 'quantity': 61},
{'name': 'Sapphire Hammer', 'quantity': 1},
{'name': 'Scarab Amulet', 'quantity': 141},
{'name': 'Scarab Shield', 'quantity': 17},
{'name': 'Shadow Sceptre', 'quantity': 208},
{'name': 'Shockwave Amulet', 'quantity': 21},
{'name': 'Silver Brooch', 'quantity': 44},
{'name': 'Silver Dagger', 'quantity': 2},
{'name': 'Skull Helmet', 'quantity': 0},
{'name': 'Skull Staff', 'quantity': 16},
{'name': 'Skullcracker Armor', 'quantity': 8},
{'name': 'Spike Sword', 'quantity': 42},
{'name': 'Spiked Squelcher', 'quantity': 124},
{'name': 'Springsprout Rod', 'quantity': 8},
{'name': 'Steel Boots', 'quantity': 43},
{'name': 'Strange Helmet', 'quantity': 2},
{'name': 'Swamplair Armor', 'quantity': 0},
{'name': 'Taurus Mace', 'quantity': 188},
{'name': 'Terra Amulet', 'quantity': 226},
{'name': 'Terra Boots', 'quantity': 177},
{'name': 'Terra Hood', 'quantity': 149},
{'name': 'Terra Legs', 'quantity': 138},
{'name': 'Terra Mantle', 'quantity': 120},
{'name': 'Terra Rod', 'quantity': 10},
{'name': 'Titan Axe', 'quantity': 18},
{'name': 'Tower Shield', 'quantity': 18},
{'name': 'Underworld Rod', 'quantity': 28},
{'name': 'Vile Axe', 'quantity': 0},
{'name': 'Wand Of Cosmic Energy', 'quantity': 181},
{'name': 'Wand Of Decay', 'quantity': 61},
{'name': 'Wand Of Draconia', 'quantity': 257},
{'name': 'Wand Of Dragonbreath', 'quantity': 36},
{'name': 'Wand Of Inferno', 'quantity': 535},
{'name': 'Wand Of Starstorm', 'quantity': 318},
{'name': 'Wand Of Voodoo', 'quantity': 28},
{'name': 'War Hammer', 'quantity': 194},
{'name': 'Warrior Helmet', 'quantity': 18}]
